### ISSUE TITLE
ESP8266 support?

### ISSUE THREAD

**Issue by spotlesscoder** [rambo/mcp23017#1]
Does this library also work for the ESP8266? In particular, the NodeMCU 1.0 (ESP-12E)

If so, please add a compatibility list to the readme so users can recognize that quickly.

**Comment by rambo** [comment]
It uses the I2C master library https://github.com/rambo/i2c so you'd have to port that first, but once that works I see no reason why this wouldn't work, it's just some simple wrapper classes around the low-level I2C API.

Of course I have not looked at this in 5 years so there might be surprises.

**Comment by spotlesscoder** [comment]
Switched back to PCF8574. Could not make the MCP23017 work for my purpose in a reasonable time
